---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-exporter
  labels:
    app.kubernetes.io/name: jaeger-exporter
    app.kubernetes.io/instance: jaeger-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jaeger-exporter
    app.kubernetes.io/instance: jaeger-exporter
