apiVersion: v1
kind: Service
metadata:
  name: {{ include "jaeger-exporter.fullname" . }}
  labels:
    {{- include "jaeger-exporter.labels" . | nindent 4 }}
    {{- with .Values.serviceLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jaeger-exporter.selectorLabels" . | nindent 4 }}
