name: Helm

on:
  push:
    paths:
      - 'deploy/helm/jaeger-exporter/**'

jobs:
  helm:
    name: Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: |
          helm lint deploy/helm/jaeger-exporter

      - name: Template
        run: |
          helm template jaeger-exporter -n tracing deploy/helm/jaeger-exporter

      - name: Install
        run: |
          kind create cluster
          sleep 60s
          kubectl create namespace tracing
          sleep 10s
          helm install --namespace tracing jaeger-exporter deploy/helm/jaeger-exporter

      - name: Configure git
        run: |
          git config --global user.email "mail@ricoberger.de" && git config --global user.name "ricoberger"

      - name: Package Helm Chart
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          helm package ./deploy/helm/jaeger-exporter

      - name: Clone Helm Repository
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git clone https://github.com/ricoberger/helm-charts.git

      - name: Update Helm Repository
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          mv jaeger-exporter* ./helm-charts/ && helm repo index helm-charts/ --url https://ricoberger.github.io/helm-charts/

      - name: Commit Changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd helm-charts/ && git add . && git commit -m "Add new release for Jaeger Exporter"

      - name: Push Changes
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cd helm-charts/ && git push https://ricoberger:${{ secrets.TOKEN }}@github.com/ricoberger/helm-charts.git
